# Generated by Django 2.2.3 on 2019-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('1', 1), ('1.5', 1.5), ('2', 2), ('2.5', 2.5), ('3', 3), ('3.5', 3.5), ('4', 4)], default='Not Yet Updated', max_length=5),
        ),
    ]
