# Generated by Django 2.2.3 on 2019-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190801_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(max_length=30),
        ),
    ]
